export const environment = {
  PRODUCTION: true,
  API_URL: 'http://www.omdbapi.com/?apikey=bf5769f2',
  RECENTLY_VIEWED_LOCALSTORAGE_KEY_NAME: 'OMDB_DATA_VIEWER_RECENTLY_VIEWED',
  LANGUAGE_LOCALSTORAGE_KEY_NAME: 'OMDB_DATA_LANG',
  START_SEARCH_TEXT_VALUE: 'Star Wars',
  MAX_RECENTLY_VIEWED: 10,
};
