export const environment = {
  PRODUCTION: false,
  API_URL: 'https://www.omdbapi.com/?apikey=bf5769f2',
  RECENTLY_VIEWED_LOCALSTORAGE_KEY_NAME: 'OMDB_DATA_VIEWER_RECENTLY_VIEWED_DEV',
  LANGUAGE_LOCALSTORAGE_KEY_NAME: 'OMDB_DATA_LANG_DEV',
  START_SEARCH_TEXT_VALUE: 'Star Wars',
  MAX_RECENTLY_VIEWED: 10,
  SNACK_BAR_DURATION: 3000,
};
